"""
Human handoff detection - deciding when the AI should stop auto-replying
to a customer and flag the conversation for a team member instead. See
api/webhook.py for where this plugs into the incoming-message pipeline,
and crm/lead_manager.py's pause_ai()/resume_ai() for how the pause itself
is stored.

Two independent triggers, both documented at their call sites in
webhook.py:

1. detect_explicit_handoff_request() - a deterministic phrase match
   against the customer's own message. Runs before the AI even generates
   a reply, so an explicit "let me talk to a person" gets a handoff
   acknowledgment instead of an unrelated AI answer bolted onto it.

2. A sentiment + intent combination (checked in webhook.py using the
   analysis dict ai/lead_intelligence.py already computes) - Negative
   sentiment alone is too noisy (a customer can be mildly annoyed about
   pricing without wanting a human), so this requires *both* Negative
   sentiment AND Complaint intent before pausing. That reply has already
   been generated by the time this is known, so it still gets sent - the
   pause only affects the customer's *next* message onward.
"""

import re


# Deliberately phrase-based rather than single keywords ("agent", "human",
# "person" alone would false-positive on completely unrelated sentences
# like "I'm the only person handling this order" or "which agent do you
# recommend"). Each pattern requires an explicit request-for-a-human
# shape, not just the word appearing somewhere in the message.
_HANDOFF_PATTERNS = [
    r"\btalk (?:to|with) (?:a |an )?(?:real )?(?:human|person|someone|agent|representative|rep|manager)\b",
    r"\bspeak (?:to|with) (?:a |an )?(?:real )?(?:human|person|someone|agent|representative|rep|manager)\b",
    r"\bconnect me (?:to|with) (?:a |an )?(?:human|person|agent|representative|rep|manager)\b",
    r"\b(?:get|send) me (?:a |an )?(?:human|real person|live agent|manager)\b",
    r"\bis there a (?:real )?(?:human|person|agent) (?:i can|available)\b",
    r"\b(?:human|live|real) (?:agent|support|assistance)\b",
    r"\bcustomer service rep(?:resentative)?\b",
    r"\bstop (?:talking to|replying with) (?:a |the )?bot\b",
    r"\b(?:not|no) a bot\b",
    r"\bthis is a bot\b",
    r"\bactual (?:person|human)\b",
]

_COMPILED_PATTERNS = [
    re.compile(pattern, re.IGNORECASE)
    for pattern in _HANDOFF_PATTERNS
]


def detect_explicit_handoff_request(text):
    """
    Returns the matched phrase if the customer's message explicitly asks
    for a human, otherwise None.
    """

    if not text:
        return None

    for pattern in _COMPILED_PATTERNS:

        match = pattern.search(text)

        if match:
            return match.group(0)

    return None


def is_negative_complaint(analysis):
    """
    True when ai/lead_intelligence.py's analysis dict indicates a genuine
    complaint - both Negative sentiment AND Complaint intent, not either
    alone. Requiring both avoids pausing AI on every mildly frustrated
    message (e.g. Negative sentiment + Pricing Inquiry intent shouldn't
    trigger a handoff by itself).
    """

    if not analysis:
        return False

    return (
        analysis.get("sentiment") == "Negative"
        and analysis.get("intent") == "Complaint"
    )
